[pytest]
DJANGO_SETTINGS_MODULE = frontend_server.settings
pythonpath = environment/frontend_server
markers =
    slow: marks tests as slow (deselect with -m "not slow")
addopts = -p no:cacheprovider -m "not slow"